// package namespace for our app
package com.example.weatherpal.view;
// android class for navigating between activities
import android.content.Intent;
// android class for passing data and saving state information
import android.os.Bundle;
// android class for displaying toast messages
import android.widget.Toast;
// android class for enabling edge-to-edge display; i.e. content behind system bars
import androidx.activity.EdgeToEdge;
// basic android Activity class; includes backwards compatibility features
import androidx.appcompat.app.AppCompatActivity;
// class for handling system insets like status bars, nav bar areas, etc
import androidx.core.graphics.Insets;
// import for backwards compatibility with View operations
import androidx.core.view.ViewCompat;
// for handling insets in a backwards-compatible manner
import androidx.core.view.WindowInsetsCompat;
// our auto-generated binding class for our activity_login.xml file
import com.example.weatherpal.R;
import com.example.weatherpal.databinding.ActivityLoginBinding;
// import for our app's MainActivity class
// class for handling Firebase functionality, like logins, auth, registrations
import com.google.firebase.auth.FirebaseAuth;

public class LoginActivity extends AppCompatActivity {

    // firebase
    // variable to hold our firebase authorization object
    // which gives us access to firebase authentication methods
    private FirebaseAuth mAuth;

    //binding
    // holds a reference to our activity_login.xml
    ActivityLoginBinding binding;

    @Override
    // override the onCreate function and pass in the app's previously saved instance state
    protected void onCreate(Bundle savedInstanceState) {
        // calls the oncreate() method from our parent class AppCompatActivity
        super.onCreate(savedInstanceState);
        // enables edge-to-edge display for our LoginActivity view
        EdgeToEdge.enable(this);
        // binding setCOntent
        // inflates/displays the layout as defined in activity_login.xml and assigns that value to our binding variable
        binding = ActivityLoginBinding.inflate(getLayoutInflater());
        // makes our current view the result of calling the core information of our binding variable
        // more specifically, it calls the top-level ViewGroup from that .xml; i.e. the root of our layout
        setContentView(binding.getRoot());

        // autogenerated portion of code that's created when new project is created
        // standard boilerplate for edge-to-edge support
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });

        // week 11 code referred to for below:
        // calls the getInstance() method from the FirebaseAuth class
        // and assigns the result to our current firebase connection object
        // FirebaseAuth class knows to get our connection info from the google-services.json file
        mAuth = FirebaseAuth.getInstance();

        // binding for switching to register screen
        // sets an onclick listener to the registerNow view/button in our bound .xml, i.e. login_activity.xml
        // pass in the view that was clicked as the parameter
        binding.registerNav.setOnClickListener(view -> {
            /* creation new intent object, with two parameters:
            - the app's context, which is used to start the activity
            - the target activity class that should be navigated to
            basically, this intent tells the android system that we want to start the RegisterActivity
            */
            Intent intObj = new Intent(getApplicationContext(), RegisterActivity.class);
            // call method to start an activity, and pass in our intent object as assigned above
            startActivity(intObj);
            // prevent backstack
            finish();
        });

        //login (hard coded user)
        // set a click listener to the login button in our .xml file
        // pass in the view that's being clicked on, i.e. that login button
        binding.loginBtn.setOnClickListener(view -> {
            // grab users inputs
            // calls methods on email and password views in bound .xml
            // assigns the values to email and password variables
            String userEmail = binding.email.getText().toString().trim();
            String userPassword = binding.password.getText().toString().trim();

            if (userEmail.isEmpty()  || userPassword.isEmpty()) {
                Toast.makeText(LoginActivity.this, "Please enter a valid email and password.", Toast.LENGTH_SHORT).show();
            }
            else {
                // apply information to registering the user
                // call the loginUser method (as defined below) and pass in email and password parameters as inputted by user
                loginUser(userEmail, userPassword);
            }
        });
    }

    // defines function to log in the user using their email and password inputs
    private void loginUser(String email, String password) {
        // toast message that appears when loginUser() is initially called
        Toast.makeText(this, "Loading User...", Toast.LENGTH_SHORT).show();
        // call two built-in methods from the firebase class
        // we call these on our firebase authorization object
        // signInWithEmailAndPassword() attempts to login user and return a Task<AuthResult> object, i.e. a Firebase task
        // addOnCompleteListener() listens for result of login attempt
        mAuth.signInWithEmailAndPassword(email, password).addOnCompleteListener(this, task -> {
            // if our login attempt/task is successful, we show a toast message displaying the result
            if (task.isSuccessful()) {
                Toast.makeText(LoginActivity.this, "Successfully Logged-In", Toast.LENGTH_SHORT).show();
                // we then define a new intent object that can take us to our MainActivity activity/class
                Intent intObj = new Intent(getApplicationContext(), MainActivity.class);
                // we start that activity by passing in our intent
                startActivity(intObj);
                // include this to avoid backstack
                finish();
            } else {
                // if task/login not successful, display failed login message with task's exception/error details
                // think maybe the exception details could be a logcat message instead?
                // not sure what kind of message/technical details it would expose to the user
                Toast.makeText(LoginActivity.this, "Failed Logging-In." + task.getException(),
                        Toast.LENGTH_SHORT).show();
            }
        });
    }
}