package com.example.weatherpal.view;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;
// seems like an autogenerated R class that needs to be imported?
import com.example.weatherpal.R;
import com.example.weatherpal.model.WeatherModel;
import java.util.List;

/* Class purpose:
- Connector class between API data (i.e. WeatherModel) and RecyclerView (MainActivity)
- Our adapter class extends the built-in RecyclerView class. */

// based on code from recyclerview lesson
public class MyAdapter extends RecyclerView.Adapter<MyAdapter.MyViewHolder>{

    // our data source
    // to-do: figure out how to handle with this with dynamic api data instead of a list of hardcoded values
    // modified from itemList to weatherModelList; List parameter changed from Item to WeatherModel
    private final List<WeatherModel> weatherModelList;

    // click listener
    public ItemClickListener clickListener;
    //constructor for our adapter class
    public MyAdapter(List<WeatherModel> weatherModelList) {
        this.weatherModelList = weatherModelList;
    }

    // define logic for our onclick listener
    // we pass in myListener value as the parameter
    // and assign this class's clickListener value to the myListener parameter we've passed in
    public void setClickListener(ItemClickListener myListener){
        this.clickListener = myListener;
    }

    // Implemented Methods (Overrides) //

    @NonNull
    @Override
    public MyViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(parent.getContext()).inflate(R.layout.activity_weather_detail,parent, false);
        return new MyViewHolder(itemView);
    }

    @Override
    public void onBindViewHolder(@NonNull MyViewHolder holder, int position) {
        // binds our api data to the views within the view holder
        WeatherModel weatherModel = weatherModelList.get(position);
        // need to figure out how we get these values; i don't see ids in .xml file i don't think?
        // but they must be there cause we display the city and region at the top of the detailed page
        /* holder.city.setText(weatherModel.getCity());
        holder.region.setText(weatherModel.getRegion()); */
        holder.weatherCondition.setText(weatherModel.getWeatherCondition());
        holder.tempC.setText(weatherModel.getTempC());
        holder.tempF.setText(weatherModel.getTempF());
        holder.wind.setText(weatherModel.getWind());
        holder.humidity.setText(weatherModel.getHumidity());
        holder.feelsLikeC.setText(weatherModel.getFeelsLikeC());
        holder.feelsLikeF.setText(weatherModel.getFeelsLikeF());
        holder.windChillC.setText(weatherModel.getWindChillC());
        holder.windChillF.setText(weatherModel.getWindChillF());
        holder.uvIndex.setText(weatherModel.getUvIndex());
    }

    @Override
    public int getItemCount() {
        return weatherModelList.size();
    }

    // Additional code //
    // class within a class
    public class MyViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener{
        // variables for each bit of api data that gets displayed on the details page
        TextView city;
        TextView region;
        TextView weatherCondition;
        TextView tempC;
        TextView tempF;
        TextView wind;
        TextView humidity;
        TextView feelsLikeC;
        TextView feelsLikeF;
        TextView windChillC;
        TextView windChillF;
        TextView uvIndex;

        // constructor for our class within a class; i.e. called whenever a new ViewHolder is created
        // parameter View itemView is the inflated layout that's passed, i.e an entire item/row
        public MyViewHolder(@NonNull View itemView) {
            // this calls the parent class's constructor, i.e. RecyclerView.ViewHolder
            // since MyViewHolder extends RecyclerView.ViewHolder, we need the parent class for things to work properly
            super(itemView);
            // then we find all the views that correspond with our api data

            // don't see any id for city or region in activty_weather_detail.xml?
            /* city = itemView.findViewById(R.id.city);
            region = itemView.findViewById(R.id.region); */
            weatherCondition = itemView.findViewById(R.id.weatherCondition);
            tempC = itemView.findViewById(R.id.tempC);
            tempF = itemView.findViewById(R.id.tempF);
            wind = itemView.findViewById(R.id.wind);
            humidity = itemView.findViewById(R.id.humidity);
            feelsLikeC = itemView.findViewById(R.id.feelsLikeC);
            feelsLikeF = itemView.findViewById(R.id.feelsLikeF);
            windChillC = itemView.findViewById(R.id.windChillC);
            windChillF = itemView.findViewById(R.id.windChillF);
            uvIndex = itemView.findViewById(R.id.uvIndex);
            // and then we make this constructor's entire group of attributes clickable
            itemView.setOnClickListener(this);
        }

        //implemented method after adding implements View.OnClickListener
        @Override
        public void onClick(View view) {
            if (clickListener != null) {
                clickListener.onClick(view,getAdapterPosition());
            }
        }
    }

}
