package com.example.weatherpal.view;

import android.annotation.SuppressLint;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;
// seems like an autogenerated R class that needs to be imported?
import com.example.weatherpal.R;
import com.example.weatherpal.databinding.ItemLayoutBinding;
import com.example.weatherpal.model.WeatherModel;
import java.util.List;

/* Class purpose:
- Connector class between WeatherModel and RecyclerView (SearchFragment)
- Our adapter class extends the built-in RecyclerView class. */

// based on code from recyclerview lesson
public class MyAdapter extends RecyclerView.Adapter<MyAdapter.MyViewHolder>{

    // our data source
    // modified from itemList to weatherModelList; List parameter changed from Item to WeatherModel
    private final List<WeatherModel> weatherModelList;

    // click listener
    public ItemClickListener clickListener;
    //constructor for our adapter class
    public MyAdapter(List<WeatherModel> weatherModelList) {
        this.weatherModelList = weatherModelList;
    }

    // define logic for our onclick listener
    // we pass in myListener value as the parameter
    // and assign this class's clickListener value to the myListener parameter we've passed in
    public void setClickListener(ItemClickListener myListener){
        this.clickListener = myListener;
    }

    // Implemented Methods (Overrides) //

    @NonNull
    @Override
    public MyViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        ItemLayoutBinding binding =
                ItemLayoutBinding.inflate(LayoutInflater.from(parent.getContext()), parent, false);
        return new MyViewHolder(binding);
    }

    @SuppressLint("SetTextI18n")
    @Override
    public void onBindViewHolder(@NonNull MyViewHolder holder, int position) {
        // binds our api data to the views within the view holder
        WeatherModel weatherModel = weatherModelList.get(position);
        holder.binding.weatherIcon.setImageResource(weatherModel.getWeatherIcon());
        holder.binding.city.setText(weatherModel.getCity());
        holder.binding.regionCountry.setText(weatherModel.getRegion()+", "+ weatherModel.getCountry());
        holder.binding.latLon.setText(String.valueOf(weatherModel.getLatitude()+", "+ weatherModel.getLongitude()));
    }

    @Override
    public int getItemCount() {
        return weatherModelList.size();
    }

    // Additional code //
    // class within a class
    public class MyViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener{
        // added binding as we cannot use viewByID anywhere in assign
        ItemLayoutBinding binding; //binds for the item_layout.xml

        // variables for each bit of api data that gets displayed in the RecyclerView
//        TextView city;
//        TextView region;
//        ImageView weatherIcon;

        // constructor for our class within a class; i.e. called whenever a new ViewHolder is created
        // parameter View itemView is the inflated layout that's passed, i.e an entire item/row
        public MyViewHolder(ItemLayoutBinding binding) {
            // this calls the parent class's constructor, i.e. RecyclerView.ViewHolder
            // since MyViewHolder extends RecyclerView.ViewHolder, we need the parent class for things to work properly
            super(binding.getRoot());
            this.binding = binding;
            binding.getRoot().setOnClickListener(this);
            // api data shown within the RecyclerView
            // no viewbyID allowed

            // and then we make this constructor's entire group of attributes clickable
//            itemView.setOnClickListener(this);
        }

        //implemented method after adding implements View.OnClickListener
        @Override
        public void onClick(View view) {
            if (clickListener != null) {
                clickListener.onClick(view,getAdapterPosition());
            }
        }
    }

}
